"""initial tables

Revision ID: c73d4a0b0c3e
Revises: 
Create Date: 2026-02-18 11:11:19.513796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c73d4a0b0c3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash for deduplication'),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True, comment='JSON-encoded document metadata'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_documents_content_hash'))
    )
    op.create_index(op.f('ix_documents_ingested_at'), 'documents', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False, comment='Resolved canonical name for entity linking'),
    sa.Column('type', sa.String(length=64), nullable=False, comment='Entity type: PERSON, ORG, GPE, DATE, EVENT, etc.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True, comment='JSON array of known aliases'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True, comment='action, state_change, declaration, occurrence'),
    sa.Column('ts_start', sa.DateTime(timezone=True), nullable=True, comment='Event start timestamp (UTC)'),
    sa.Column('ts_end', sa.DateTime(timezone=True), nullable=True, comment='Event end timestamp (UTC), null if point-in-time'),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False, comment='NLP extraction confidence score 0.0-1.0'),
    sa.Column('source_sentence', sa.Text(), nullable=True, comment='Original sentence from which event was extracted'),
    sa.Column('embedding', Vector(384), nullable=True, comment='Dense vector embedding for semantic search'),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_events_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_document_id'), 'events', ['document_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_ts_start'), 'events', ['ts_start'], unique=False)
    op.create_table('causal_relations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cause_event_id', sa.UUID(), nullable=False),
    sa.Column('effect_event_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False, comment='Confidence score for this causal link 0.0-1.0'),
    sa.Column('evidence', sa.Text(), nullable=True, comment='The phrase or sentence indicating this causal relationship'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cause_event_id'], ['events.id'], name=op.f('fk_causal_relations_cause_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['effect_event_id'], ['events.id'], name=op.f('fk_causal_relations_effect_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_causal_relations'))
    )
    op.create_index(op.f('ix_causal_relations_cause_event_id'), 'causal_relations', ['cause_event_id'], unique=False)
    op.create_index(op.f('ix_causal_relations_effect_event_id'), 'causal_relations', ['effect_event_id'], unique=False)
    op.create_table('event_entities',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_event_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_entities_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'entity_id', name=op.f('pk_event_entities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_entities')
    op.drop_index(op.f('ix_causal_relations_effect_event_id'), table_name='causal_relations')
    op.drop_index(op.f('ix_causal_relations_cause_event_id'), table_name='causal_relations')
    op.drop_table('causal_relations')
    op.drop_index(op.f('ix_events_ts_start'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_document_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_ingested_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
